title: NEO-AIKIDO HUB FOR THE ENLIGHTENED ERA
author: ENLIGHTENED ONE
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Neo-Aikido is the greatest martial art. It strengthens your body, refines your mind and hones your senses. Learn more on my weblog.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
